### ISSUE TITLE
Non-linearity in Res2Net

### ISSUE THREAD

**Issue by tea1528** [lxtGH/OctaveConv_pytorch#18]
@lxtGH, thanks for the great repo.

I just have a question regarding your implementation of Res2Net. Your implementation has sub-convolution along with BN & ReLU. 

[https://github.com/lxtGH/OctaveConv_pytorch/blob/master/libs/nn/res2net.py#L57](https://github.com/lxtGH/OctaveConv_pytorch/blob/master/libs/nn/res2net.py#L57)

However, I couldn't find any mention of non-linearity in the paper so it is bit unclear to me. Have you tested the performance with & without non-linearity? I think adding BN & ReLU to every sub conv might slow down the training process.

**Comment by lxtGH** [comment]
Hi ! sorry for late reply. @tea1528 It seems like the orginal paper didn't use non-linearity but with BN.
https://github.com/gasvn/Res2Net/blob/master/res2net.py#L49-L50

**Comment by lxtGH** [comment]
The new commit is the same with origin paper.
