### ISSUE TITLE
Strided convolutions handled incorrectly

### ISSUE THREAD

**Issue by andravin** [lxtGH/OctaveConv_pytorch#2]
**Edit** 

Now I am not so sure, since a careful reading of the papers seems to show the authors believe that strided convolutions cause misaligned feature maps, which is an erroneous conclusion. I go into more detail in the linked issue, below.

---

**Original issue text**

https://github.com/lxtGH/OctaveConv_pytorch/blob/83b4cc1d1575733ac598fe834c5cf357102b4238/nn/OctaveConv2.py#L93

I don't think strided convolutions receive any special treatment in the paper. I think maybe there was some confusion about the discussion of how downsampling is implemented. That refers to the H->L downsampling operation, it does not refer to the way a strided convolution layer is ported to OctConv.

Since the paper is not explicit about strided convolutions, I assume they are ported to OctConv just as any other convolutional layer. So I would just use the given stride argument in each of the convolutions, L->L, L->H, H->L, H-H.

Unless somebody finds information to the contrary, this appears to be the only sensible reading of the paper.

**Comment by lxtGH** [comment]
Hi! I have considered your idea: just use stride=2 in convolution layer. I mainly reference this MXnet [repo](https://github.com/terrychenism/OctaveConv) for implementation.

**Comment by andravin** [comment]
Thanks, I opened an issue there: https://github.com/terrychenism/OctaveConv/issues/4

**Comment by andravin** [comment]
For anybody who stumbles upon this issue, the reference implementation for OctConv has been available for sometime now, here:
https://github.com/facebookresearch/OctConv

**Comment by lxtGH** [comment]
Thanks for your kind reply!!!
