### ISSUE TITLE
there is a bug in line 38?

### ISSUE THREAD

**Issue by liujiaheng** [lxtGH/OctaveConv_pytorch#4]
![image](https://user-images.githubusercontent.com/27964642/56347785-9bc97b80-61f7-11e9-9af5-175a21a1a42c.png)

**Comment by SmartWB** [comment]
Have you solve it ? I have the same problem.

**Comment by JiahuanChen** [comment]
Should be something like this.
    def forward(self, x):
        X_h, X_l = x

        if self.stride ==2:
            X_h, X_l = self.h2g_pool(X_h), self.h2g_pool(X_l)

        X_h2l = self.h2g_pool(X_h)

        X_h2h = self.h2h(X_h)
        X_l2h = self.l2h(X_l)

        X_l2l = self.l2l(X_l)
        X_h2l = self.h2l(X_h2l)
        
        X_l2h = self.upsample(X_l2h)
        X_h = X_l2h + X_h2h
        X_l = X_h2l + X_l2l

        return X_h, X_l

**Comment by lxtGH** [comment]
Hi, please check new version.
