### ISSUE TITLE
AdaptiveConv通道数不对

### ISSUE THREAD

**Issue by splinter22** [lxtGH/OctaveConv_pytorch#5]
https://github.com/lxtGH/OctaveConv_pytorch/blob/master/nn/AdaptiveConvResnet.py
158行

forward:3x3后的x1，in->out，通道数为out
而作为fc1的输入，通道数为in

**Comment by splinter22** [comment]
另外，upsample，就一个像素，为何不用F.upsample(ca, size=size, mode="nearest")，
F.upsample(ca, size=size, mode="bilinear", align_corners=True)浪费很多计算量

**Comment by lxtGH** [comment]
1. https://github.com/wanggrun/Adaptively-Connected-Neural-Networks/blob/c39928837ca5441820f64d82cc20d4dff410776a/cnn/dataset-aware/gr_conv.py#L37
我是根据这个行改的,fc1的out通道数和conv3x3一致。
2. 已修改,但是我本地测试没发现inference速度有很大的差别.
