### ISSUE TITLE
Handling different input and output number of channels in AdaptiveConv

### ISSUE THREAD

**Issue by shivamsaboo17** [lxtGH/OctaveConv_pytorch#7]
In this line shouldn't we pass x to gap, otherwise if our input and output number of channels is different this will throw error, because x1 will have different number of channels than x and fc1 layers maps from number of input channels to number of output channels. 
``` python
gap = self.gap(x1)
```
Please let me know  if I am missing something.

**Comment by lxtGH** [comment]
Hi! Many thanks for your advice, I didn't notice this mistake, I have fix this bug in new commit.
