### ISSUE TITLE
tensor dimension mismatching

### ISSUE THREAD

**Issue by harudaee** [lxtGH/OctaveConv_pytorch#8]
Dear Sir, when I use nn.OCtaveResnet in image classification--input image size is [224,224,3], batch_size=72-- the shape of X_l2h doesn't match X_h2h (from OCtaveConv2--OCtaveConv).

<img width="197" alt="WeChat597ca554349433817b1cda84c4e65668" src="https://user-images.githubusercontent.com/46665745/56560584-677b0400-65d7-11e9-957a-5f4b0ae3586f.png">

it seems that it is something wrong with upsample. I don't know how to fix it

**Comment by lxtGH** [comment]
Input 224 * 224 -> L_H: 14*14 L_l: 7 * 7(7 is odd) after pooling the L_l then up-sample(with scale factor 2) lead un-aligned results.
1. Large crop size: like 256
2. modify upsample using "size" parameter.
